---
- name: Update dns entry
  hosts: dns
  tasks:
    - name: Append to hosts file
      ansible.builtin.lineinfile:
        insertafter: EOF
        state: present
        path: /etc/hosts
        line: "{{ dns_entry_addr_ipv4 }} {{ dns_entry_name }}"
      when: dns_entry_addr_ipv4 is defined
      notify: Restart dnsmasq
    - name: Append to hosts file
      ansible.builtin.lineinfile:
        insertafter: EOF
        state: present
        path: /etc/hosts
        line: "{{ dns_entry_addr_ipv6 }} {{ dns_entry_name }}"
      when: dns_entry_addr_ipv6 is defined
      notify: Restart dnsmasq

  handlers:
    - name: Restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted
      failed_when: false # might fail if dnsmasq isnt installed yet so we ignore the error (there are smarter ways to do this)
