collections:
  - name: https://github.com/prometheus-community/ansible.git
    version: main
    type: git
  - name: grafana.grafana
  - name: community.docker
roles:
  - name: promtail
    src: https://github.com/patrickjahns/ansible-role-promtail
    scm: git
  - name: node_exporter
    src: https://github.com/geerlingguy/ansible-role-node_exporter
    scm: git
  - name: adguard
    src: https://github.com/bcook254/ansible-role-adguardhome
    scm: git
  - src: https://github.com/O1ahmad/ansible-role-systemd
    scm: git
    name: 0x0i.systemd
    version: master
  - name: wireguard
    src: https://github.com/githubixx/ansible-role-wireguard
    scm: git
    version: master
  - name: ngine_io.blocky_dns
    src: https://github.com/ngine-io/ansible-role-blocky-dns