---
collections:
  - name: https://github.com/prometheus-community/ansible.git
    version: main
    type: git
  - name: grafana.grafana
  - name: community.docker
  - name: ansible.posix
roles:
  - name: promtail
    src: https://github.com/patrickjahns/ansible-role-promtail
    scm: git
  - name: node_exporter
    src: https://github.com/geerlingguy/ansible-role-node_exporter
    scm: git
  - name: wireguard
    src: https://github.com/githubixx/ansible-role-wireguard
    scm: git
    version: master
  - name: ngine_io.blocky_dns
    src: https://github.com/ngine-io/ansible-role-blocky-dns
    version: main
