---
- name: Install step ca
  hosts: ca
  become: true
  pre_tasks:
    - name: Install compression libary
      ansible.builtin.package:
        name: tar
        state: present
      become: true
  tasks:
    - name: Install step-ca
      ansible.builtin.include_role:
        name: maxhoesel.smallstep.step_ca
      vars:
        step_ca_name: "{{ ca_name }}"
        step_ca_root_password: "{{ ca_password }}"
        step_ca_intermediate_password: "{{ ca_password }}"
        step_ca_ssh: "{{ ca_ssh }}"
    - name: Add an ACME provisioner to the CA
      maxhoesel.smallstep.step_ca_provisioner:
        name: ACME
        type: ACME
      become: true
      become_user: step-ca
      notify: Reload step-ca
    - name: Get fingerpint
      ansible.builtin.command: "step-cli certificate fingerprint /etc/step-ca/certs/root_ca.crt"
      register: root_ca_fp
      changed_when: root_ca_fp.rc != 0
    - name: Write fingerpint to file
      ansible.builtin.copy:
        content: "{{ root_ca_fp.stdout }}"
        dest: ./root_ca_fp
        mode: "0755"
      delegate_to: localhost
      become: true
      become_user: olivia # find way to dynamically change user
  handlers:
    - name: Reload step-ca
      ansible.builtin.systemd:
        name: step-ca
        state: reloaded
