---
- name: Setup dns servers
  hosts: dns
  tasks:
    - name: Install dns server
      ansible.builtin.include_role:
        name: ngine_io.blocky_dns
      vars:
        blocky__hosts_dns_enabled: "{{ host_dns_enabled }}"
        blocky__hosts_dns_domain: ".dialgatrainer.duckdns.org"
  pre_tasks:
    - name: Install compression libary
      ansible.builtin.package:
        name: tar
        state: present
      become: true
