---
- name: Install dns server
  hosts: default
  roles: 
    # - maxhoesel.smallstep.step_ca
    - bertvv.dnsmasq
  # pre_tasks:
    # - name: Make hosts.d
      # ansible.builtin.file:
        # state: directory
        # name: /etc/hosts.d/
        # mode: "0755"
        # owner: root
        # group: root
      # when: dnsmasq_blocklists is defined
    # - name: Add blocklists
      # ansible.builtin.get_url:
        # url: "{{ item }}"
        # dest: /etc/hosts.d/{{ idx }}-host
        # mode: "0755"
        # owner: root
        # group: root
      # loop: "{{ dnsmasq_blocklists }}"
      # loop_control:
        # index_var: idx
      # when: dnsmasq_blocklists is defined
  # tasks:
    # - name: Install dnsmasq
      # ansible.builtin.include_role:
        # name: bertvv.dnsmasq

  handlers:
    - name: Restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted