---
    # - name: Install grafana alloy
    # hosts: all
    # tasks:
    # - name: Install grafana alloy
    # ansible.builtin.include_role:
    # name: grafana.grafana.alloy
    # vars:
    # alloy_config: "{{ grafana_alloy_config }}"

- name: Install and configure Minio Server
  hosts: minio
  become: true
  pre_tasks:
    - name: Install package epel-release
      ansible.builtin.dnf:
        name: epel-release
        state: present
    - name: Install python3-virtualenv
      ansible.builtin.dnf:
        enablerepo:
          - crb
        name:
          - python3-virtualenv
        state: present
    - name: Slurp cert file from host
      ansible.builtin.slurp:
        path: "/etc/ssl/step.crt"
      register: minio_crt_b64
    - name: Slurp key file from host
      ansible.builtin.slurp:
        path: "/etc/ssl/step.key"
      register: minio_key_b64
    - name: Load tls key and cert
      ansible.builtin.set_fact:
        minio_key: "{{ minio_key_b64['content'] | b64decode }}"
        minio_cert: "{{ minio_crt_b64['content'] | b64decode }}"
  tasks:
    - name: Install minio
      ansible.builtin.include_role:
        name: ricsanfre.minio
  vars:
    minio_validate_certificate: "{{ validate_certificate }}"
    minio_alias: "{{ alias }}"
    minio_buckets: "{{ minio_buckets }}"
    minio_users: "{{ minio_users }}"
    minio_root_user: "{{ minio_root_user }}"
    minio_root_password: "{{ minio_root_password }}"
    minio_enable_tls: "{{ minio_enable_tls }}"
    minio_url: "{{ minio_url }}"

- name: Install grafana mimir
  hosts: mimr
  tasks:
    - name: Install grafana mimir
      ansible.builtin.include_role:
        name: grafana.grafana.mimir
  vars:
    mimir_storage: "{{ object_storage }}"
    mimir_blocks_storage: "{{ block_storage }}"
