---
collections:
  - name: maxhoesel.smallstep
    version: main
    source: git+https://github.com/maxhoesel-ansible/ansible-collection-smallstep
    type: git
roles: 
    - name: ngine_io.blocky_dns
      src: https://github.com/ngine-io/ansible-role-blocky-dns
      version: main