---
- name: Install step ca
  hosts: ca
  become: true
  pre_tasks:
    - name: Install compression libary
      ansible.builtin.package:
        name: tar
        state: present
      become: true
  tasks:
    # Install and initialize the CA server.
    # There are a lot of configuration options, see the step_ca README for details
    - name: Install step-ca
      ansible.builtin.include_role:
        name: maxhoesel.smallstep.step_ca
      vars:
        step_ca_name: "{{ ca_name }}"
        step_ca_root_password: "{{ ca_password }}"
        step_ca_intermediate_password: "{{ ca_password }}"
        step_ca_ssh: true
