---
- name: Configure a wireguard tunnel
  hosts: wireguard
  pre_tasks:
    - name: Set ip forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
    - name: Set ipv6 forwarding
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: 1
        reload: true
  tasks:
    - name: Configure wireguard
      ansible.builtin.include_role:
        name: githubixx.ansible_role_wireguard
      vars:
        ansible_become: true
- name: Add route to all other hosts
  hosts: all:1wireguard
  tasks:
    - name: Add static route
      ansible.builtin.template:
        src: wg_route.service.j2
        dest: /etc/systemd/system/wg_route.service
        mode: "0644"
        owner: root
        group: root
    - name: Enable the route
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: wg_route
        enabled: true
        state: started
