---
- name: Setup Arr stack with Buildarr
  hosts: arrstack
  become: true
  vars_files:
    ../variables.yml
  roles:
    - arrstack
  tags:
    - arrstack
  # post_tasks:
    # - name: Add prowlarr indexers
      # 