---
- name: Setup dns servers
  hosts: dns
  roles:
    - role: ngine_io.blocky_dns
  vars:
    blocky__hosts_dns_enabled: true
    blocky__hosts_dns_domain: .hn-1-prx.duckdns.org
  tags:
    - dns-servers
    - bootstrap
