---
- name: Setup dns servers
  hosts: dns
  roles:
    - role: ngine_io.blocky_dns
  vars:
    blocky_hosts_dns_enabled: true
    blocky_hosts_dns_domain: .olivia420.duckdns.org
- name: Change all dns servers to point at dns servers
  hosts: all:!dns
  tasks:
    - name: Make pve ignore resolv conf # find way to diffrenciate between lxc and not
      ansible.builtin.file:
        name: /etc/.pve-ignore.resolv
        state: touch
        mode: "0777"
      become: true
    - name: Insert name servers into resolv conf
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          for connection in $(nmcli con show --active | grep ethernet | awk '{print $3 }');
          do nmcli con mod "$connection" ipv4.dns "{{ hostvars["adguard1"].ansible_host | ansible.builtin.ipv4 }} {{ hostvars["adguard2"].ansible_host | ansible.builtin.ipv4 }}";
          done
  tags:
    - dns-servers
    - adguard
