---
- name: Install matrics and log exporters
  hosts: all:!laptop
  become: true
  vars_files:
    ../variables.yml
  roles:
    - role: node_exporter
      tags:
        - node_exporter
    - role: promtail
      tags:
        - promtail
  post_tasks:
    - name: Reload promtail
      ansible.builtin.systemd_service:
        name: promtail
        state: restarted
      tags:
        - promtail

- name: Install and setup prometheus
  hosts: prometheus
  vars_files:
    ../variables.yml
  roles:
    - prometheus.prometheus.prometheus
  post_tasks:
    - name: Add file sd targets
      ansible.builtin.template:
        src: ../templates/targets.yml.j2 # noqa: no-relative-paths
        dest: /etc/prometheus/file_sd/node.yml
        mode: "755"
        owner: prometheus
        group: prometheus
      tags:
        - prometheus
        - service_discovery
  tags:
    - prometheus
- name: Install and setup loki
  hosts: loki
  roles:
    - role: loki
  tags:
    - loki
- name: Install and setup granfana
  hosts: grafana
  roles:
    - role: grafana.grafana.grafana
  vars_files:
    ../variables.yml
  tags:
    - grafana
