---
- name: Install minecraft in docker Compose
  hosts: minecraft
  pre_tasks:
    - name: Remove podman docker
      ansible.builtin.dnf:
        name:
          - docker
          - podman-docker
          - podman
        state: absent
      become: true
    - name: Add docker ce repo
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
    - name: Update dnf
      ansible.builtin.dnf:
        name: "*"
        state: latest
      become: true
    - name: Install docker
      ansible.builtin.dnf:
        name:
          - docker-ce
        state: latest
      become: true
    - name: Start docker service
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true
      become: true
  tasks:
    - name: Create minecraft dir
      ansible.builtin.file:
        name: /opt/minecraft
        state: directory
        mode: "0755"
        owner: root
        group: root
      become: true
    - name: Copy compose file
      ansible.builtin.copy:
        src: ../files/docker-compose-minecraft.yml
        dest: /opt/minecraft/docker-compose.yml
        owner: root
        group: root
        mode: "0755"
      become: true
    - name: Start doker compose
      community.docker.docker_compose_v2:
        project_name: minecraft_server
        project_src: /opt/minecraft
      become: true
  tags:
    - minecraft
